### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by deprid** [SilvDev/Reload_Fix-Max_Clip_Size#1]
The details link in the readme leads to Left 4 DHooks Direct page. The correct link should be the one in the .sp file which is: https://forums.alliedmods.net/showthread.php?t=327105

Just a small thing to fix xD. Btw thanks for being persistent in helping SM especially L4D2 community for more than a decade!

**Comment by SilvDev** [comment]
Thanks! Fixed
